# Generated by Django 5.2.9 on 2025-12-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations_portalcms_django', '0002_rename_news_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationnews',
            options={'ordering': ['-created_at'], 'verbose_name': 'Integration News', 'verbose_name_plural': 'Integration News'},
        ),
        migrations.AlterModelOptions(
            name='systemstatusnews',
            options={'ordering': ['-created_at'], 'verbose_name': 'System Status News', 'verbose_name_plural': 'System Status News'},
        ),
        migrations.AlterModelTable(
            name='integrationnews',
            table='djangocmsjoy_integrationnews',
        ),
        migrations.AlterModelTable(
            name='systemstatusnews',
            table='djangocmsjoy_systemstatusnews',
        ),
        migrations.DeleteModel(
            name='AccessNews',
        ),
    ]
