# Generated by Django 5.2.9 on 2026-01-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations_portalcms_django', '0004_integrationnewsitemplugin_systemstatusnewsitemplugin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='integrationnews',
            table='operations_portalcms_django_integrationnews',
        ),
        migrations.AlterModelTable(
            name='systemstatusnews',
            table='operations_portalcms_django_systemstatusnews',
        ),
    ]
