# Generated by Django 5.2.9 on 2026-02-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_portalcms_django', '0005_alter_integrationnews_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstatusnews',
            options={'ordering': ['-created_at'], 'verbose_name': 'System and Infrastructure Status News', 'verbose_name_plural': 'System and Infrastructure Status News'},
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='affected_element',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='news_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
