"""
Django settings for Operations Portal CMS project.

Generated by 'django-admin startproject' using Django 5.2.9.
Enhanced framework drafted by Claude Sonnet 4.5 (January 28, 2026)

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if it exists (for local development)
env_file = BASE_DIR / '.env'
if env_file.exists():
    from dotenv import load_dotenv
    load_dotenv(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-_ynz3i!)8i_0=(ul2q$-^bfedijur*n!icr+reqbdvf(t*0j3b'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cms',
    'menus',
    'treebeard',
    'sekizai',
    'django_bootstrap5',
    'operations_portalcms_django',
    # Django CMS plugins
    'djangocms_text_ckeditor',
    'djangocms_picture',
    'djangocms_file',
    'djangocms_link',
    'djangocms_video',
    # Django Filer
    'filer',
    'easy_thumbnails',
    'mptt',
    # Blog dependencies (blog itself enabled below after first migration)
    'parler',
    'taggit',
    'taggit_autosuggest',
    'meta',
    'sortedm2m',
    'aldryn_apphooks_config',
    # 'djangocms_blog',  # Enable after creating BlogConfig
    # socialaccount info
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.cilogon',
    # access_django_users app
    'access_django_user_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'operations_portalcms_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'operations_portalcms_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_DATABASE', 'portalcms1'),
        'USER': os.environ.get('DJANGO_USER', 'portalcms_django'),
        'PASSWORD': os.environ.get('DJANGO_PASS', ''),
        'HOST': os.environ.get('DB_HOSTNAME_WRITE', os.environ.get('DB_HOSTNAME_READ', 'localhost')),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SITE_ID = 1

# Django CMS Settings
CMS_CONFIRM_VERSION4 = True
CMS_TEMPLATES = [
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
    ('infrastructure.html', 'Infrastructure Integration'),
    ('blog.html', 'Blog Post'),
]
CMS_PERMISSION = False
CMS_PLACEHOLDER_CONF = {}
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Blog Settings
META_SITE_PROTOCOL = 'http'
META_USE_SITES = True
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True

BLOG_ENABLE_COMMENTS = False
BLOG_USE_PLACEHOLDER = True
BLOG_IMAGE_THUMBNAIL_SIZE = {'size': '800x450', 'crop': True}
BLOG_IMAGE_FULL_SIZE = {'size': '1200x675', 'crop': True}
BLOG_PAGINATION = 10
BLOG_LATEST_POSTS = 5
BLOG_POSTS_LIST_TRUNCWORDS_COUNT = 100
BLOG_AUTHOR_DEFAULT = True  # Auto-set current user as author
BLOG_USE_ABSTRACT = True  # Enable abstract/excerpt field
BLOG_MULTISITE = False  # Single site setup
BLOG_AVAILABLE_PERMALINK_STYLES = (
    ('full_date', 'Full date'),
    ('short_date', 'Year /Month'),
    ('category', 'Category'),
    ('slug', 'Just slug'),
)
BLOG_PERMALINK_STYLE = 'slug'  # Simple URL structure

# Thumbnail Settings
THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)
THUMBNAIL_PRESERVE_EXTENSIONS = True
THUMBNAIL_ALIASES = {
    '': {
        'default': {'size': (300, 300), 'crop': True},
        'large': {'size': (800, 600), 'crop': False},
    },
}

# Text Editor Settings
TEXT_SAVE_IMAGE_FUNCTION = 'djangocms_text_ckeditor.picture_save.create_picture_plugin'
TEXT_ADDITIONAL_TAGS = ('iframe',)
TEXT_ADDITIONAL_ATTRIBUTES = ('scrolling', 'allowfullscreen', 'frameborder')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Application Logging
APP_LOG = os.environ.get('APP_LOG', str(BASE_DIR / 'var' / 'portalcms.log'))
APP_VERSION = os.environ.get('APP_VERSION', 'dev')
SYSLOG_SOCK = os.environ.get('SYSLOG_SOCK', '/var/run/syslog')

# API Configuration
API_BASE = os.environ.get('API_BASE', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
